# Use official Python image
FROM python:3.12-slim

# Set work directory
WORKDIR /app

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app
COPY . .

# Run the application using Uvicorn
CMD ["uvicorn", "launch:app", "--host", "0.0.0.0", "--port", "80", "--workers", "4"]
